--require("bufferline").setup{

--highlights = {
            --fill = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            -----------background = {
			-----------fg = '#928374',
			--bg = '',
            -----------},
            --tab = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --tab_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --tab_close = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --close_button = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --close_button_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --close_button_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            -------------buffer_visible = {
			-------------fg = '#928374',
			-------------bg = '',
            ------------},
            ------------buffer_selected = {
			------------fg = '#fe8019',
			--bg = '',
            -----------},
            --numbers = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --numbers_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --numbers_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --diagnostic = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --diagnostic_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --diagnostic_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --hint = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --hint_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --hint_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --hint_diagnostic = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --hint_diagnostic_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --hint_diagnostic_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --info = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --info_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --info_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --info_diagnostic = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --info_diagnostic_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --info_diagnostic_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --warning = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --warning_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --warning_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --warning_diagnostic = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --warning_diagnostic_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            ---warning_diagnostic_selected = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --error = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --error_visible = {
			--fg = '#fafaf7',
			--bg = '',
            --},
            --error_selected = {
           	--fg = '#fafaf7',
		--bg = '',
            --},
            --error_diagnostic = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --error_diagnostic_visible = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --error_diagnostic_selected = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --modified = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --modified_visible = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --modified_selected = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --duplicate_selected = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --duplicate_visible = {
                 	--fg = '#fafaf7',
			--bg = '',
            --},
            --duplicate = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --separator_selected = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --separator_visible = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --separator = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
       		 ----------------indicator_selected = {
                	---------fg = '#fafaf7',
			-----------------bg = '',
            ----------------},
            --pick_selected = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --pick_visible = {
                	--fg = '#fafaf7',
			        --bg = '',
           -- },
            --pick = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
            --offset_separator = {
                	--fg = '#fafaf7',
			--bg = '',
            --},
        -----------},
	------------options = {
	    -------show_close_icon = false,
	    ---------show_buffer_icons = false,
	    --------show_buffer_close_icons = false,
	    ---------separator_style = {''},
	 -------indicator = {
                --icon = '﬌', -- this should be omitted if indicator style is not 'icon'
                --------style = 'none',
            ---},
	---------}

 ---------}

